### ISSUE TITLE
Add Storefront UI to the list

### ISSUE THREAD

**Issue by Baroshem** [ddahan/ui-libs#17]
Hey there!

Really nice list of UI libs to use in your next Vue project.

I would like to recommend to add https://vuestorefront.io/storefront-ui to the list.

I can create a PR if you agree this library to the list :)

**Comment by ddahan** [comment]
Hi there!
Take a look to this issue: https://github.com/ddahan/ui-libs/issues/4
Storefront is in the review list but we're trying to find a way to have less libraries

**Comment by filrak** [comment]
Though that would be the only library focused on eCommerce which is a popular use case.I am biased, I built it but I still think my comment is relevant:)
