### ISSUE TITLE
Bug Report: UI-Libs Night Mode Toggle Issue

### ISSUE THREAD

**Issue by HarryYGit** [ddahan/ui-libs#31]
URL: https://ui-libs.vercel.app/

Description: When attempting to switch from day mode to night mode using the toggle button, the button icon does not update to reflect the change from day to night mode. The button icon remains static, regardless of the mode that is currently active.

Steps to Reproduce:

Open the website at https://ui-libs.vercel.app/.
Locate the button for toggling between day mode and night mode.
Click the button to switch from day mode to night mode.
Observe that the button icon does not change to indicate the current mode (i.e., it does not switch from a sun icon to a moon icon or vice versa).
Expected Behavior: When toggling between day mode and night mode, the button icon should update to visually represent the selected mode. For example, the icon should change from a sun to a moon when switching to night mode, and vice versa.

Actual Behavior: The button icon remains unchanged regardless of the mode switch. The icon does not update to reflect the active mode.

Screenshots: Please attach screenshots if available to show the issue.

Browser and Version:

Browser: [google chrome]
Operating System: [Windows 11]

Additional Information:

The mode switch functionality itself appears to work correctly, as the website’s color scheme changes appropriately.
The issue seems to be isolated to the button icon not updating.
Severity: Medium

Suggested Fix: Ensure that the button icon updates according to the active mode. Verify that the correct icon is applied when toggling between day and night modes and that any related CSS or JavaScript responsible for the icon update is functioning as expected.

Thank you for addressing this issue!
![Screenshot 2024-09-16 165718](https://github.com/user-attachments/assets/151a0863-5720-4a84-8a66-7cf1b20c0f41)
![Screenshot 2024-09-16 165749](https://github.com/user-attachments/assets/59f55d14-e08d-4e7e-a6f8-76cf367d4a97)
![Screenshot 2024-09-16 165800](https://github.com/user-attachments/assets/af86e92d-9de8-4adf-9d61-041e4562e44a)

**Comment by ddahan** [comment]
Hi there.
As you can see on [this file](https://github.com/ddahan/ui-libs/blob/main/components/ThemeSelector.vue), there are 3 states used by the Toogle switch. One is the system mode. So it's not a bug if the theme stays the same sometimes when clicking on the icon. What can be confusing to you is that the system icon is a sun too. I'll change that later.
Feel free to reopen if I missed something.

**Comment by HarryYGit** [comment]
Thanks for the update.
